# Imports


In [3]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler

from sklearn.model_selection import train_test_split, StratifiedKFold

import pickle

##from Classification import Classification
##from Ensemble import Ensemble

In [4]:
sns.set_context('poster')

In [6]:
x_train = pd.read_csv(r'C:\Users\lenovo\PycharmProjects\pythonProject2\Data\Trainn-Test\x_train_data.csv')
y_train = pd.read_csv(r'C:\Users\lenovo\PycharmProjects\pythonProject2\Data\Trainn-Test\y_train_data.csv')

In [7]:
x_test = pd.read_csv(r'C:\Users\lenovo\PycharmProjects\pythonProject2\Data\Trainn-Test\x_test_data.csv')
y_test = pd.read_csv(r'C:\Users\lenovo\PycharmProjects\pythonProject2\Data\Trainn-Test\y_test_data.csv')

In [8]:
print(x_train.shape)
print(y_train.shape)

(23917, 194)
(23917, 1)


In [10]:
x_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23917 entries, 0 to 23916
Columns: 194 entries, able to year
dtypes: float64(194)
memory usage: 35.4 MB


In [11]:
y_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23917 entries, 0 to 23916
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   rating  23917 non-null  int64
dtypes: int64(1)
memory usage: 187.0 KB


In [12]:
y_train = y_train.fillna((y_train.mean()))

In [13]:
y_train = y_train.astype(np.int64)

# Train and Validation Split

In [14]:
x_train, x_val, y_train, y_val = train_test_split(x_train,y_train['rating'],test_size=.25,random_state=42)

In [15]:
skf = StratifiedKFold(n_splits=5,random_state=42,shuffle=True)

# Modelling

# LogisticRegression

In [16]:
from sklearn.linear_model import LogisticRegression

pipe = make_pipeline(StandardScaler(), LogisticRegression())
Log_reg = pipe.fit(x_train, y_train)  # apply scaling on training data

In [17]:
Log_reg.score(x_val, y_val)

0.5441471571906354

Cross Validation

In [19]:
from sklearn.model_selection import cross_val_score
cross_val_score(Log_reg, x_val, y_val, cv=5)

array([0.49247492, 0.53846154, 0.52173913, 0.50585284, 0.54013378])

**Grid Search** Çalışmıyor

In [20]:
from sklearn.model_selection import GridSearchCV

params = {'penalty':['l2'],
          'C':[0.01,0.05,0.1,0.5,1,5,10]}

grid_log_reg = make_pipeline(StandardScaler(), 
                    GridSearchCV(LogisticRegression(random_state=0),
                                 params,
                                 cv=5,
                                 refit=True))

In [21]:
y_train_ravel = y_train.values.ravel()

In [22]:
grid_log_reg.fit(x_train, y_train_ravel);

In [23]:
grid_log_reg.best_estimator_

AttributeError: 'Pipeline' object has no attribute 'best_estimator_'

# Decision Tree

In [24]:
from sklearn.datasets import load_iris
from sklearn.model_selection import cross_val_score
from sklearn.tree import DecisionTreeClassifier

pipe = make_pipeline(StandardScaler(), DecisionTreeClassifier(random_state=0))
dec_tree_1 = pipe.fit(x_train, y_train)  # apply scaling on training data

In [25]:
pipe.score(x_val, y_val)

0.3887959866220736

Cross Validation

In [26]:
from sklearn.model_selection import train_test_split
cross_val_score(dec_tree_1, x_val, y_val, cv=5)

array([0.39548495, 0.38294314, 0.40217391, 0.37207358, 0.42558528])

Grid Search

In [27]:
from sklearn.model_selection import GridSearchCV

params = {'min_samples_leaf':[3,5,10,15,30,50,100],
          'max_depth':[3,4,5,6,7,8,9]}

grid = GridSearchCV(DecisionTreeClassifier(random_state=0), params, cv=7)

In [28]:
grid.fit(x_train, y_train);

In [29]:
grid.best_params_

{'max_depth': 9, 'min_samples_leaf': 100}

In [32]:
print(grid.best_estimator_)

DecisionTreeClassifier(max_depth=9, min_samples_leaf=100, random_state=0)


Best Estimator

In [33]:
pipe = make_pipeline(StandardScaler(), DecisionTreeClassifier(max_depth=9,min_samples_leaf=100,random_state=0))
pipe.fit(x_train,y_train)

Pipeline(steps=[('standardscaler', StandardScaler()),
                ('decisiontreeclassifier',
                 DecisionTreeClassifier(max_depth=9, min_samples_leaf=100,
                                        random_state=0))])

In [34]:
pipe.score(x_val, y_val)

0.442809364548495

Grid Search 2

In [35]:
from sklearn.model_selection import GridSearchCV

params = {'min_samples_leaf':[3,4,5],
          'max_depth':[7,8,9,10]}

grid = GridSearchCV(DecisionTreeClassifier(random_state=0), params, cv=7)

In [36]:
grid.fit(x_train, y_train);

In [37]:
grid.best_params_

{'max_depth': 10, 'min_samples_leaf': 3}

In [38]:
grid.best_estimator_

DecisionTreeClassifier(max_depth=10, min_samples_leaf=3, random_state=0)

Best Estimator 2

In [39]:
pipe = make_pipeline(StandardScaler(), DecisionTreeClassifier(max_depth=10, min_samples_leaf=5, random_state=0))
pipe.fit(x_train,y_train)

Pipeline(steps=[('standardscaler', StandardScaler()),
                ('decisiontreeclassifier',
                 DecisionTreeClassifier(max_depth=10, min_samples_leaf=5,
                                        random_state=0))])

In [40]:
pipe.score(x_val, y_val)

0.4270903010033445

# Random Forest

In [292]:
from sklearn.ensemble import RandomForestClassifier

In [300]:
pipe= RandomForestClassifier(max_depth=2, random_state=0)
random_forest = pipe.fit(x_train, y_train)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  


In [301]:
random_forest.score(x_val, y_val)

0.36538461538461536

Cross Validation

In [302]:
cross_val_score(random_forest, x_val, y_val, cv=5)

array([0.36538462, 0.36538462, 0.36538462, 0.36538462, 0.36538462])

Grid Search

In [303]:
from sklearn.model_selection import GridSearchCV

params = {'min_samples_leaf':[3,5,10,15,30,50,100],
          'max_depth':[3,5,7,9,11,13,15]}

grid = GridSearchCV(RandomForestClassifier(random_state=0), params, cv=7)

In [307]:
grid.fit(x_train, y_train_ravel);

KeyboardInterrupt: ignored

In [ ]:
grid.best_params_