# Imports


In [172]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler

from sklearn.model_selection import train_test_split, StratifiedKFold

import pickle

##from Classification import Classification
##from Ensemble import Ensemble

In [6]:
sns.set_context('poster')

In [153]:
x_train = pd.read_csv('/content/x_train_data.csv')
y_train = pd.read_csv('/content/y_train_data.csv')

In [154]:
x_test = pd.read_csv('/content/x_test_data.csv')
y_test = pd.read_csv('/content/y_test_data.csv')

In [19]:
print(x_train.shape)
print(y_train.shape)

(23917, 212)
(23917, 1)


In [245]:
y_train = y_train.fillna((y_train.mean()))

In [246]:
y_train = y_train.astype(np.int64)

# Train and Validation Split

In [20]:
x_train, x_val, y_train, y_val = train_test_split(x_train,y_train['rating'],test_size=.25,random_state=42)

In [21]:
skf = StratifiedKFold(n_splits=5,random_state=42,shuffle=True)

# Modelling

# LogisticRegression

In [210]:
from sklearn.linear_model import LogisticRegression

pipe = make_pipeline(StandardScaler(), LogisticRegression())
Log_reg = pipe.fit(x_train, y_train)  # apply scaling on training data

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [211]:
Log_reg.score(x_val, y_val)

0.5377926421404682

Cross Validation

In [212]:
from sklearn.model_selection import train_test_split
cross_val_score(Log_reg, x_val, y_val, cv=5)

array([0.4958194 , 0.53762542, 0.51588629, 0.50919732, 0.53762542])

**Grid Search** Çalışmıyor

In [283]:
from sklearn.model_selection import GridSearchCV

params = {'penalty':['l2'],
          'C':[0.01,0.05,0.1,0.5,1,5,10]}

grid_log_reg = make_pipeline(StandardScaler(), 
                    GridSearchCV(LogisticRegression(random_state=0),
                                 params,
                                 cv=5,
                                 refit=True))

In [281]:
y_train_ravel = y_train.values.ravel()

In [284]:
grid_log_reg.fit(x_train, y_train_ravel);

In [285]:
grid_log_reg.best_estimator_

AttributeError: ignored

# Decision Tree

In [179]:
from sklearn.datasets import load_iris
from sklearn.model_selection import cross_val_score
from sklearn.tree import DecisionTreeClassifier

pipe = make_pipeline(StandardScaler(), DecisionTreeClassifier(random_state=0))
dec_tree_1 = pipe.fit(x_train, y_train)  # apply scaling on training data

In [174]:
pipe.score(x_val, y_val)

0.38929765886287626

Cross Validation

In [184]:
from sklearn.model_selection import train_test_split
cross_val_score(dec_tree_1, x_val, y_val, cv=5)

array([0.40050167, 0.39799331, 0.39297659, 0.39214047, 0.41722408])

Grid Search

In [186]:
from sklearn.model_selection import GridSearchCV

params = {'min_samples_leaf':[3,5,10,15,30,50,100],
          'max_depth':[3,4,5,6,7,8,9]}

grid = GridSearchCV(DecisionTreeClassifier(random_state=0), params, cv=7)

In [187]:
grid.fit(x_train, y_train);

In [188]:
grid.best_params_

{'max_depth': 9, 'min_samples_leaf': 100}

In [196]:
grid.best_estimator_

DecisionTreeClassifier(max_depth=9, min_samples_leaf=100, random_state=0)

Best Estimator

In [197]:
pipe = make_pipeline(StandardScaler(), DecisionTreeClassifier(max_depth=9,min_samples_leaf=100,random_state=0))
pipe.fit(x_train,y_train)

Pipeline(steps=[('standardscaler', StandardScaler()),
                ('decisiontreeclassifier',
                 DecisionTreeClassifier(max_depth=9, min_samples_leaf=100,
                                        random_state=0))])

In [198]:
pipe.score(x_val, y_val)

0.4359531772575251

Grid Search 2

In [286]:
from sklearn.model_selection import GridSearchCV

params = {'min_samples_leaf':[3,4,5],
          'max_depth':[7,8,9,10]}

grid = GridSearchCV(DecisionTreeClassifier(random_state=0), params, cv=7)

In [287]:
grid.fit(x_train, y_train);

In [288]:
grid.best_params_

{'max_depth': 10, 'min_samples_leaf': 5}

In [289]:
grid.best_estimator_

DecisionTreeClassifier(max_depth=10, min_samples_leaf=5, random_state=0)

Best Estimator 2

In [290]:
pipe = make_pipeline(StandardScaler(), DecisionTreeClassifier(max_depth=10, min_samples_leaf=5, random_state=0))
pipe.fit(x_train,y_train)

Pipeline(steps=[('standardscaler', StandardScaler()),
                ('decisiontreeclassifier',
                 DecisionTreeClassifier(max_depth=10, min_samples_leaf=5,
                                        random_state=0))])

In [291]:
pipe.score(x_val, y_val)

0.4274247491638796

# Random Forest

In [292]:
from sklearn.ensemble import RandomForestClassifier

In [300]:
pipe= RandomForestClassifier(max_depth=2, random_state=0)
random_forest = pipe.fit(x_train, y_train)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  


In [301]:
random_forest.score(x_val, y_val)

0.36538461538461536

Cross Validation

In [302]:
cross_val_score(random_forest, x_val, y_val, cv=5)

array([0.36538462, 0.36538462, 0.36538462, 0.36538462, 0.36538462])

Grid Search

In [303]:
from sklearn.model_selection import GridSearchCV

params = {'min_samples_leaf':[3,5,10,15,30,50,100],
          'max_depth':[3,5,7,9,11,13,15]}

grid = GridSearchCV(RandomForestClassifier(random_state=0), params, cv=7)

In [307]:
grid.fit(x_train, y_train_ravel);

KeyboardInterrupt: ignored

In [ ]:
grid.best_params_